-- Próbka bazy w wersji schematu 31.
-- Plik ZAMROŻONY: zmienia się wyłącznie przez
--     python tests/test_migracje.py --zapisz
-- Ręczna edycja mija się z celem — to punkt odniesienia, nie kod.
BEGIN TRANSACTION;
CREATE TABLE do_zrobienia (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, tytul TEXT NOT NULL, opis TEXT, priorytet TEXT, szacowany_koszt REAL, termin TEXT, zadanie_id INTEGER, wykonane INTEGER DEFAULT 0, data_utworzenia TEXT, zdalne_id TEXT, zdalny_hash TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE, FOREIGN KEY (zadanie_id) REFERENCES zadania(id) ON DELETE SET NULL);
INSERT INTO "do_zrobienia" VALUES(1,1,'do_zrobienia-tytul-1','do_zrobienia-opis-1','Wysoki',10.5,'do_zrobienia-termin-1',1,1,'2021-02-11','do_zrobienia-zdalne_id-1','do_zrobienia-zdalny_hash-1');
INSERT INTO "do_zrobienia" VALUES(2,2,'do_zrobienia-tytul-2','do_zrobienia-opis-2','Średni',20.5,'do_zrobienia-termin-2',2,0,'2022-03-12','do_zrobienia-zdalne_id-2','do_zrobienia-zdalny_hash-2');
CREATE TABLE historia (id INTEGER PRIMARY KEY AUTOINCREMENT, wizyta_id INTEGER, zadanie_id INTEGER NOT NULL, data TEXT, przebieg INTEGER, kategoria TEXT, cena REAL DEFAULT 0.0, wykonawca TEXT, zalacznik TEXT, zdalne_id TEXT, zdalny_hash TEXT, dodane_przez TEXT, zmodyfikowane_przez TEXT, data_modyfikacji TEXT, FOREIGN KEY (wizyta_id) REFERENCES wizyty(id) ON DELETE CASCADE, FOREIGN KEY (zadanie_id) REFERENCES zadania(id) ON DELETE CASCADE);
INSERT INTO "historia" VALUES(1,1,1,'2021-02-11',51500,'historia-kategoria-1',10.5,'historia-wykonawca-1','historia-zalacznik-1','historia-zdalne_id-1','historia-zdalny_hash-1','historia-dodane_przez-1','historia-zmodyfikowane_przez-1','2021-02-11');
INSERT INTO "historia" VALUES(2,2,2,'2022-03-12',53000,'historia-kategoria-2',0.0,'historia-wykonawca-2','historia-zalacznik-2','historia-zdalne_id-2','historia-zdalny_hash-2','historia-dodane_przez-2','historia-zmodyfikowane_przez-2','2022-03-12');
CREATE TABLE historia_czesci_magazynu (id INTEGER PRIMARY KEY AUTOINCREMENT, historia_id INTEGER NOT NULL, magazyn_id INTEGER NOT NULL, ilosc_uzyta REAL NOT NULL DEFAULT 1, zdalne_id TEXT, zdalny_hash TEXT, FOREIGN KEY (historia_id) REFERENCES historia(id) ON DELETE CASCADE, FOREIGN KEY (magazyn_id) REFERENCES magazyn_czesci(id) ON DELETE CASCADE);
INSERT INTO "historia_czesci_magazynu" VALUES(1,1,1,10.5,'historia_czesci_magazynu-zdalne_id-1','historia_czesci_magazynu-zdalny_hash-1');
INSERT INTO "historia_czesci_magazynu" VALUES(2,2,2,20.5,'historia_czesci_magazynu-zdalne_id-2','historia_czesci_magazynu-zdalny_hash-2');
CREATE TABLE inne_koszty (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, data TEXT NOT NULL, kategoria TEXT NOT NULL, nazwa TEXT, kwota REAL NOT NULL, tagi TEXT, zalacznik TEXT, zdalne_id TEXT, zdalny_hash TEXT, dodane_przez TEXT, zmodyfikowane_przez TEXT, data_modyfikacji TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "inne_koszty" VALUES(1,1,'2021-02-11','Ogólne','inne_koszty-nazwa-1',10.5,'inne_koszty-tagi-1','inne_koszty-zalacznik-1','inne_koszty-zdalne_id-1','inne_koszty-zdalny_hash-1','inne_koszty-dodane_przez-1','inne_koszty-zmodyfikowane_przez-1','2021-02-11');
INSERT INTO "inne_koszty" VALUES(2,2,'2022-03-12','Mandaty i opłaty drogowe','inne_koszty-nazwa-2',20.5,'inne_koszty-tagi-2','inne_koszty-zalacznik-2','inne_koszty-zdalne_id-2','inne_koszty-zdalny_hash-2','inne_koszty-dodane_przez-2','inne_koszty-zmodyfikowane_przez-2','2022-03-12');
CREATE TABLE kolejka_sync (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, powod TEXT, proby INTEGER NOT NULL DEFAULT 0, ostatnia_proba TEXT, nastepna_proba TEXT, ostatni_blad TEXT);
INSERT INTO "kolejka_sync" VALUES(1,1,'kolejka_sync-powod-1',1,'kolejka_sync-ostatnia_proba-1','kolejka_sync-nastepna_proba-1','kolejka_sync-ostatni_blad-1');
INSERT INTO "kolejka_sync" VALUES(2,2,'kolejka_sync-powod-2',2,'kolejka_sync-ostatnia_proba-2','kolejka_sync-nastepna_proba-2','kolejka_sync-ostatni_blad-2');
CREATE TABLE kosz_pojazdy (id INTEGER PRIMARY KEY AUTOINCREMENT, nazwa TEXT NOT NULL, data_usuniecia TEXT NOT NULL, migawka TEXT NOT NULL, pliki TEXT, liczba_wpisow INTEGER NOT NULL DEFAULT 0, rozmiar_plikow INTEGER NOT NULL DEFAULT 0, schemat_wersja INTEGER);
INSERT INTO "kosz_pojazdy" VALUES(1,'kosz_pojazdy-nazwa-1','2026-09-07 22:39:29','{"wersja": 1, "auto": {"kolumny": [], "wiersz": {}}, "tabele": {}}','[]',1,1,1);
INSERT INTO "kosz_pojazdy" VALUES(2,'kosz_pojazdy-nazwa-2','2026-09-07 22:39:29','{"wersja": 1, "auto": {"kolumny": [], "wiersz": {}}, "tabele": {}}','[]',2,2,2);
CREATE TABLE magazyn_czesci (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, nazwa TEXT NOT NULL, kategoria TEXT, ilosc REAL NOT NULL DEFAULT 1, jednostka TEXT DEFAULT 'szt', cena REAL, data_zakupu TEXT, notatki TEXT, zalacznik TEXT, prog_ostrzezenia REAL DEFAULT 1, zdalne_id TEXT, zdalny_hash TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "magazyn_czesci" VALUES(1,1,'magazyn_czesci-nazwa-1','Płyny eksploatacyjne',10.5,'szt',10.5,'2021-02-11','magazyn_czesci-notatki-1','magazyn_czesci-zalacznik-1',10.5,'magazyn_czesci-zdalne_id-1','magazyn_czesci-zdalny_hash-1');
INSERT INTO "magazyn_czesci" VALUES(2,2,'magazyn_czesci-nazwa-2','Oleje i smary',20.5,'szt',20.5,'2022-03-12','magazyn_czesci-notatki-2','magazyn_czesci-zalacznik-2',1.0,'magazyn_czesci-zdalne_id-2','magazyn_czesci-zdalny_hash-2');
CREATE TABLE odczyty_przebiegu (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, data TEXT NOT NULL, przebieg INTEGER NOT NULL, zdalne_id TEXT, zdalny_hash TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "odczyty_przebiegu" VALUES(1,1,'2021-02-11',51500,'odczyty_przebiegu-zdalne_id-1','odczyty_przebiegu-zdalny_hash-1');
INSERT INTO "odczyty_przebiegu" VALUES(2,2,'2022-03-12',53000,'odczyty_przebiegu-zdalne_id-2','odczyty_przebiegu-zdalny_hash-2');
CREATE TABLE pakiety_serwisowe_wlasne (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, nazwa TEXT NOT NULL, pozycje TEXT NOT NULL, zdalne_id TEXT, zdalny_hash TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "pakiety_serwisowe_wlasne" VALUES(1,1,'pakiety_serwisowe_wlasne-nazwa-1','pakiety_serwisowe_wlasne-pozycje-1','pakiety_serwisowe_wlasne-zdalne_id-1','pakiety_serwisowe_wlasne-zdalny_hash-1');
INSERT INTO "pakiety_serwisowe_wlasne" VALUES(2,2,'pakiety_serwisowe_wlasne-nazwa-2','pakiety_serwisowe_wlasne-pozycje-2','pakiety_serwisowe_wlasne-zdalne_id-2','pakiety_serwisowe_wlasne-zdalny_hash-2');
CREATE TABLE samochody (id INTEGER PRIMARY KEY AUTOINCREMENT, nazwa TEXT UNIQUE NOT NULL, oc_data TEXT, przeglad_data TEXT, nr_rej TEXT, vin TEXT, rok_produkcji TEXT, pojemnosc_silnika TEXT, moc_silnika TEXT, typ_paliwa TEXT, skrzynia_biegow TEXT, notatki TEXT, wycieraczki_przod TEXT, wycieraczki_tyl TEXT, cisnienie_przod TEXT, cisnienie_tyl TEXT, olej_typ TEXT, olej_pojemnosc TEXT, akumulator TEXT, zarowki_mijania TEXT, zarowki_drogowe TEXT, ac_data TEXT, assistance_data TEXT, gasnica_data TEXT, apteczka_data TEXT, zdjecie_glowne TEXT, marka TEXT, model TEXT, generacja TEXT, kolor_motywu TEXT, wspolny_pojazd_id TEXT, kod_zaproszenia TEXT, info_zdalne_id TEXT, zdalny_hash_info TEXT, wiadomosc_statusu TEXT, gwarancja_data TEXT, gwarancja_przebieg INTEGER);
INSERT INTO "samochody" VALUES(1,'Pojazd 1','2021-02-11','2021-02-11','samochody-nr_rej-1','samochody-vin-1','samochody-rok_produkcji-1','samochody-pojemnosc_silnika-1','samochody-moc_silnika-1','Elektryczny','samochody-skrzynia_biegow-1','samochody-notatki-1','samochody-wycieraczki_przod-1','samochody-wycieraczki_tyl-1','samochody-cisnienie_przod-1','samochody-cisnienie_tyl-1','samochody-olej_typ-1','samochody-olej_pojemnosc-1','samochody-akumulator-1','samochody-zarowki_mijania-1','samochody-zarowki_drogowe-1','2021-02-11','2021-02-11','2021-02-11','2021-02-11','samochody-zdjecie_glowne-1','samochody-marka-1','samochody-model-1','samochody-generacja-1','samochody-kolor_motywu-1','samochody-wspolny_pojazd_id-1','samochody-kod_zaproszenia-1','samochody-info_zdalne_id-1','samochody-zdalny_hash_info-1','samochody-wiadomosc_statusu-1','2021-02-11',1);
INSERT INTO "samochody" VALUES(2,'Pojazd 2','2022-03-12','2022-03-12','samochody-nr_rej-2','samochody-vin-2','samochody-rok_produkcji-2','samochody-pojemnosc_silnika-2','samochody-moc_silnika-2','Benzyna','samochody-skrzynia_biegow-2','samochody-notatki-2','samochody-wycieraczki_przod-2','samochody-wycieraczki_tyl-2','samochody-cisnienie_przod-2','samochody-cisnienie_tyl-2','samochody-olej_typ-2','samochody-olej_pojemnosc-2','samochody-akumulator-2','samochody-zarowki_mijania-2','samochody-zarowki_drogowe-2','2022-03-12','2022-03-12','2022-03-12','2022-03-12','samochody-zdjecie_glowne-2','samochody-marka-2','samochody-model-2','samochody-generacja-2','samochody-kolor_motywu-2','samochody-wspolny_pojazd_id-2','samochody-kod_zaproszenia-2','samochody-info_zdalne_id-2','samochody-zdalny_hash_info-2','samochody-wiadomosc_statusu-2','2022-03-12',2);
CREATE TABLE tagi (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, nazwa TEXT NOT NULL, kolor TEXT NOT NULL, zdalne_id TEXT, zdalny_hash TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "tagi" VALUES(1,1,'tagi-nazwa-1','tagi-kolor-1','tagi-zdalne_id-1','tagi-zdalny_hash-1');
INSERT INTO "tagi" VALUES(2,2,'tagi-nazwa-2','tagi-kolor-2','tagi-zdalne_id-2','tagi-zdalny_hash-2');
CREATE TABLE tankowania (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, data TEXT NOT NULL, przebieg INTEGER NOT NULL, dystans REAL NOT NULL DEFAULT 0.0, litry REAL NOT NULL, kwota REAL NOT NULL, do_pelna INTEGER DEFAULT 1, stacja TEXT, tagi TEXT, zalacznik TEXT, zdalne_id TEXT, zdalny_hash TEXT, dodane_przez TEXT, zmodyfikowane_przez TEXT, data_modyfikacji TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "tankowania" VALUES(1,1,'2021-02-11',51500,10.5,10.5,10.5,1,'tankowania-stacja-1','tankowania-tagi-1','tankowania-zalacznik-1','tankowania-zdalne_id-1','tankowania-zdalny_hash-1','tankowania-dodane_przez-1','tankowania-zmodyfikowane_przez-1','2021-02-11');
INSERT INTO "tankowania" VALUES(2,2,'2022-03-12',53000,20.5,20.5,20.5,1,'tankowania-stacja-2','tankowania-tagi-2','tankowania-zalacznik-2','tankowania-zdalne_id-2','tankowania-zdalny_hash-2','tankowania-dodane_przez-2','tankowania-zmodyfikowane_przez-2','2022-03-12');
CREATE TABLE ustawienia (klucz TEXT PRIMARY KEY, wartosc TEXT);
INSERT INTO "ustawienia" VALUES('schema_version','31');
INSERT INTO "ustawienia" VALUES('ostatnia_zakladka','2');
CREATE TABLE warsztaty (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, nazwa TEXT NOT NULL, telefon TEXT, adres TEXT, notatki TEXT, zdalne_id TEXT, zdalny_hash TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "warsztaty" VALUES(1,1,'warsztaty-nazwa-1','warsztaty-telefon-1','warsztaty-adres-1','warsztaty-notatki-1','warsztaty-zdalne_id-1','warsztaty-zdalny_hash-1');
INSERT INTO "warsztaty" VALUES(2,2,'warsztaty-nazwa-2','warsztaty-telefon-2','warsztaty-adres-2','warsztaty-notatki-2','warsztaty-zdalne_id-2','warsztaty-zdalny_hash-2');
CREATE TABLE wizyta_czesci_magazynu (id INTEGER PRIMARY KEY AUTOINCREMENT, wizyta_id INTEGER NOT NULL, magazyn_id INTEGER NOT NULL, ilosc_uzyta REAL NOT NULL DEFAULT 1, zdalne_id TEXT, zdalny_hash TEXT, FOREIGN KEY (wizyta_id) REFERENCES wizyty(id) ON DELETE CASCADE, FOREIGN KEY (magazyn_id) REFERENCES magazyn_czesci(id) ON DELETE CASCADE);
INSERT INTO "wizyta_czesci_magazynu" VALUES(1,1,1,10.5,'wizyta_czesci_magazynu-zdalne_id-1','wizyta_czesci_magazynu-zdalny_hash-1');
INSERT INTO "wizyta_czesci_magazynu" VALUES(2,2,2,20.5,'wizyta_czesci_magazynu-zdalne_id-2','wizyta_czesci_magazynu-zdalny_hash-2');
CREATE TABLE wizyty (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, data TEXT NOT NULL, przebieg INTEGER NOT NULL, wykonawca TEXT, koszt_calkowity REAL NOT NULL DEFAULT 0.0, notatki TEXT, tagi TEXT, zalacznik TEXT, zdalne_id TEXT, zdalny_hash TEXT, dodane_przez TEXT, zmodyfikowane_przez TEXT, data_modyfikacji TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "wizyty" VALUES(1,1,'2021-02-11',51500,'wizyty-wykonawca-1',10.5,'wizyty-notatki-1','wizyty-tagi-1','wizyty-zalacznik-1','wizyty-zdalne_id-1','wizyty-zdalny_hash-1','wizyty-dodane_przez-1','wizyty-zmodyfikowane_przez-1','2021-02-11');
INSERT INTO "wizyty" VALUES(2,2,'2022-03-12',53000,'wizyty-wykonawca-2',20.5,'wizyty-notatki-2','wizyty-tagi-2','wizyty-zalacznik-2','wizyty-zdalne_id-2','wizyty-zdalny_hash-2','wizyty-dodane_przez-2','wizyty-zmodyfikowane_przez-2','2022-03-12');
CREATE TABLE wyciszone_powiadomienia (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, klucz TEXT NOT NULL, do_dnia TEXT NOT NULL, tytul TEXT, utworzono TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "wyciszone_powiadomienia" VALUES(1,1,'wyciszone_powiadomienia-klucz-1','wyciszone_powiadomienia-do_dnia-1','wyciszone_powiadomienia-tytul-1','wyciszone_powiadomienia-utworzono-1');
INSERT INTO "wyciszone_powiadomienia" VALUES(2,2,'wyciszone_powiadomienia-klucz-2','wyciszone_powiadomienia-do_dnia-2','wyciszone_powiadomienia-tytul-2','wyciszone_powiadomienia-utworzono-2');
CREATE TABLE wydatki_cykliczne (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, nazwa TEXT NOT NULL, kwota REAL NOT NULL DEFAULT 0.0, okres_dni INTEGER NOT NULL DEFAULT 30, nastepna_data TEXT NOT NULL, zdalne_id TEXT, zdalny_hash TEXT, czy_koszt INTEGER NOT NULL DEFAULT 1, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "wydatki_cykliczne" VALUES(1,1,'wydatki_cykliczne-nazwa-1',10.5,1,'2021-02-11','wydatki_cykliczne-zdalne_id-1','wydatki_cykliczne-zdalny_hash-1',1);
INSERT INTO "wydatki_cykliczne" VALUES(2,2,'wydatki_cykliczne-nazwa-2',20.5,2,'2022-03-12','wydatki_cykliczne-zdalne_id-2','wydatki_cykliczne-zdalny_hash-2',2);
CREATE TABLE zadania (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, nazwa TEXT NOT NULL, data TEXT, przebieg INTEGER, interwal_km INTEGER, interwal_miesiace INTEGER, dotyczy_opon INTEGER DEFAULT 0, zdalne_id TEXT, zdalny_hash TEXT, prog_km INTEGER, prog_dni INTEGER, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "zadania" VALUES(1,1,'Wymiana opon / Kół','2021-02-11',51500,1,1,1,'zadania-zdalne_id-1','zadania-zdalny_hash-1',1,1);
INSERT INTO "zadania" VALUES(2,2,'zadania-nazwa-2','2022-03-12',53000,2,2,0,'zadania-zdalne_id-2','zadania-zdalny_hash-2',2,2);
CREATE TABLE zdalne_nagrobki (id INTEGER PRIMARY KEY AUTOINCREMENT, tabela TEXT NOT NULL, zdalny_id TEXT NOT NULL);
INSERT INTO "zdalne_nagrobki" VALUES(1,'zdalne_nagrobki-tabela-1','zdalne_nagrobki-zdalny_id-1');
INSERT INTO "zdalne_nagrobki" VALUES(2,'zdalne_nagrobki-tabela-2','zdalne_nagrobki-zdalny_id-2');
CREATE TABLE zdjecia_karoserii (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, data TEXT NOT NULL, strefa TEXT NOT NULL, zalacznik TEXT NOT NULL, opis TEXT, przebieg INTEGER, typ_porownania TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "zdjecia_karoserii" VALUES(1,1,'2021-02-11','Przód','zdjecia_karoserii-zalacznik-1','zdjecia_karoserii-opis-1',51500,'Brak');
INSERT INTO "zdjecia_karoserii" VALUES(2,2,'2022-03-12','Tył','zdjecia_karoserii-zalacznik-2','zdjecia_karoserii-opis-2',53000,'Przed naprawą');
CREATE TABLE zestawy_opon (id INTEGER PRIMARY KEY AUTOINCREMENT, auto_id INTEGER NOT NULL, sezon TEXT, rozmiar TEXT, marka_model TEXT, glebokosc_bieznika REAL, data_pomiaru TEXT, numer_dot TEXT, ilosc INTEGER DEFAULT 4, zamontowane INTEGER DEFAULT 0, data_zakupu TEXT, przebieg_zakupu INTEGER, notatki TEXT, cena REAL DEFAULT 0.0, os_montazu TEXT DEFAULT 'Wszystkie', zalacznik TEXT, zdalne_id TEXT, zdalny_hash TEXT, FOREIGN KEY (auto_id) REFERENCES samochody(id) ON DELETE CASCADE);
INSERT INTO "zestawy_opon" VALUES(1,1,'Letnie','zestawy_opon-rozmiar-1','zestawy_opon-marka_model-1',10.5,'2021-02-11','zestawy_opon-numer_dot-1',1,1,'2021-02-11',51500,'zestawy_opon-notatki-1',10.5,'Wszystkie','zestawy_opon-zalacznik-1','zestawy_opon-zdalne_id-1','zestawy_opon-zdalny_hash-1');
INSERT INTO "zestawy_opon" VALUES(2,2,'Zimowe','zestawy_opon-rozmiar-2','zestawy_opon-marka_model-2',20.5,'2022-03-12','zestawy_opon-numer_dot-2',4,0,'2022-03-12',53000,'zestawy_opon-notatki-2',0.0,'Wszystkie','zestawy_opon-zalacznik-2','zestawy_opon-zdalne_id-2','zestawy_opon-zdalny_hash-2');
CREATE INDEX idx_warsztaty_auto ON warsztaty(auto_id);
CREATE INDEX idx_wydatki_cykliczne_auto ON wydatki_cykliczne(auto_id);
CREATE INDEX idx_zadania_auto ON zadania(auto_id);
CREATE INDEX idx_wizyty_auto ON wizyty(auto_id);
CREATE INDEX idx_tankowania_auto ON tankowania(auto_id);
CREATE INDEX idx_inne_koszty_auto ON inne_koszty(auto_id);
CREATE INDEX idx_zestawy_opon_auto ON zestawy_opon(auto_id);
CREATE INDEX idx_do_zrobienia_auto ON do_zrobienia(auto_id);
CREATE INDEX idx_tagi_auto ON tagi(auto_id);
CREATE INDEX idx_magazyn_czesci_auto ON magazyn_czesci(auto_id);
CREATE INDEX idx_zdjecia_karoserii_auto ON zdjecia_karoserii(auto_id);
CREATE INDEX idx_historia_zadanie ON historia(zadanie_id);
CREATE INDEX idx_historia_wizyta ON historia(wizyta_id);
CREATE INDEX idx_do_zrobienia_zadanie ON do_zrobienia(zadanie_id);
CREATE INDEX idx_wizyta_czesci_wizyta ON wizyta_czesci_magazynu(wizyta_id);
CREATE INDEX idx_wizyta_czesci_magazyn ON wizyta_czesci_magazynu(magazyn_id);
CREATE INDEX idx_odczyty_przebiegu_auto ON odczyty_przebiegu(auto_id);
CREATE INDEX idx_pakiety_wlasne_auto ON pakiety_serwisowe_wlasne(auto_id);
CREATE INDEX idx_tankowania_auto_zdalne ON tankowania(auto_id, zdalne_id);
CREATE INDEX idx_zadania_auto_zdalne ON zadania(auto_id, zdalne_id);
CREATE INDEX idx_wizyty_auto_zdalne ON wizyty(auto_id, zdalne_id);
CREATE INDEX idx_magazyn_czesci_auto_zdalne ON magazyn_czesci(auto_id, zdalne_id);
CREATE INDEX idx_zestawy_opon_auto_zdalne ON zestawy_opon(auto_id, zdalne_id);
CREATE INDEX idx_inne_koszty_auto_zdalne ON inne_koszty(auto_id, zdalne_id);
CREATE INDEX idx_do_zrobienia_auto_zdalne ON do_zrobienia(auto_id, zdalne_id);
CREATE INDEX idx_warsztaty_auto_zdalne ON warsztaty(auto_id, zdalne_id);
CREATE INDEX idx_wydatki_cykliczne_auto_zdalne ON wydatki_cykliczne(auto_id, zdalne_id);
CREATE INDEX idx_odczyty_przebiegu_auto_zdalne ON odczyty_przebiegu(auto_id, zdalne_id);
CREATE INDEX idx_tagi_auto_zdalne ON tagi(auto_id, zdalne_id);
CREATE INDEX idx_historia_zdalne ON historia(zdalne_id);
CREATE INDEX idx_wizyta_czesci_magazynu_zdalne ON wizyta_czesci_magazynu(zdalne_id);
CREATE INDEX idx_pakiety_wlasne_auto_zdalne ON pakiety_serwisowe_wlasne(auto_id, zdalne_id);
CREATE UNIQUE INDEX idx_kolejka_sync_auto ON kolejka_sync(auto_id);
CREATE INDEX idx_kosz_data ON kosz_pojazdy(data_usuniecia);
CREATE INDEX idx_historia_czesci_historia ON historia_czesci_magazynu(historia_id);
CREATE INDEX idx_historia_czesci_magazyn ON historia_czesci_magazynu(magazyn_id);
CREATE INDEX idx_historia_czesci_zdalne ON historia_czesci_magazynu(zdalne_id);
CREATE UNIQUE INDEX idx_wyciszone_klucz ON wyciszone_powiadomienia(auto_id, klucz);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('kolejka_sync',2);
INSERT INTO "sqlite_sequence" VALUES('kosz_pojazdy',2);
INSERT INTO "sqlite_sequence" VALUES('samochody',2);
INSERT INTO "sqlite_sequence" VALUES('zdalne_nagrobki',2);
INSERT INTO "sqlite_sequence" VALUES('inne_koszty',2);
INSERT INTO "sqlite_sequence" VALUES('magazyn_czesci',2);
INSERT INTO "sqlite_sequence" VALUES('odczyty_przebiegu',2);
INSERT INTO "sqlite_sequence" VALUES('pakiety_serwisowe_wlasne',2);
INSERT INTO "sqlite_sequence" VALUES('tagi',2);
INSERT INTO "sqlite_sequence" VALUES('tankowania',2);
INSERT INTO "sqlite_sequence" VALUES('warsztaty',2);
INSERT INTO "sqlite_sequence" VALUES('wizyty',2);
INSERT INTO "sqlite_sequence" VALUES('wyciszone_powiadomienia',2);
INSERT INTO "sqlite_sequence" VALUES('wydatki_cykliczne',2);
INSERT INTO "sqlite_sequence" VALUES('zadania',2);
INSERT INTO "sqlite_sequence" VALUES('zdjecia_karoserii',2);
INSERT INTO "sqlite_sequence" VALUES('zestawy_opon',2);
INSERT INTO "sqlite_sequence" VALUES('do_zrobienia',2);
INSERT INTO "sqlite_sequence" VALUES('historia',2);
INSERT INTO "sqlite_sequence" VALUES('wizyta_czesci_magazynu',2);
INSERT INTO "sqlite_sequence" VALUES('historia_czesci_magazynu',2);
COMMIT;
